LANGUAGES = {
  "nmg" : "Kwasio",
  "ses" : "Koyraboro Senni",
  "mgo" : "Metaʼ",
  "cv" : "Chuvash",
  "bho" : "Bhojpuri",
  "mt" : "Maltese",
  "he" : "Hebrew",
  "ky" : "Kyrgyz",
  "dv" : "Dhivehi",
  "te" : "Telugu",
  "wa" : "Walloon",
  "sa" : "Sanskrit",
  "naq" : "Nama",
  "dz" : "Dzongkha",
  "tig" : "Tigre",
  "ru" : "Russian",
  "kl" : "Kalaallisut",
  "so" : "Somali",
  "ii" : "Liangshan Yi",
  "si" : "Sinhala",
  "nd" : "North Ndebele",
  "gaa" : "Ga",
  "dje" : "Zarma",
  "kab" : "Kabyle",
  "cic" : "Chickasaw",
  "ksf" : "Bafia",
  "gsw" : "Swiss German",
  "hr" : "Croatian",
  "kln" : "Kalenjin",
  "et" : "Estonian",
  "az" : "Azerbaijani",
  "osa" : "Osage",
  "ewo" : "Ewondo",
  "lu" : "Luba-Katanga",
  "zu" : "Zulu",
  "scn" : "Sicilian",
  "wae" : "Walser",
  "ta" : "Tamil",
  "ms" : "Malay",
  "mgh" : "Makhuwa-Meetto",
  "ve" : "Venda",
  "nr" : "South Ndebele",
  "pa" : "Punjabi",
  "shi" : "Tachelhit",
  "cs" : "Czech",
  "kkj" : "Kako",
  "da" : "Danish",
  "luy" : "Luyia",
  "ber" : "Amazigh",
  "kok" : "Konkani",
  "vun" : "Vunjo",
  "nds" : "Low German",
  "su" : "Sundanese",
  "bg" : "Bulgarian",
  "yue" : "Cantonese",
  "fi" : "Finnish",
  "ig" : "Igbo",
  "rhg" : "Rohingya",
  "sv" : "Swedish",
  "nso" : "Northern Sotho",
  "ha" : "Hausa",
  "ml" : "Malayalam",
  "io" : "Ido",
  "rej" : "Rejang",
  "doi" : "Dogri",
  "lo" : "Lao",
  "pqm" : "Wolastoqey",
  "ug" : "Uyghur",
  "mi" : "Māori",
  "zh" : "Chinese",
  "id" : "Indonesian",
  "lrc" : "Northern Luri",
  "nyn" : "Nyankole",
  "is" : "Icelandic",
  "gez" : "Geez",
  "vai" : "Vai",
  "ceb" : "Cebuano",
  "lt" : "Lithuanian",
  "bgc" : "Haryanvi",
  "ln" : "Lingala",
  "tr" : "Turkish",
  "os" : "Ossetic",
  "ro" : "Romanian",
  "fo" : "Faroese",
  "ksb" : "Shambala",
  "trv" : "Taroko",
  "saq" : "Samburu",
  "eu" : "Basque",
  "lg" : "Ganda",
  "oc" : "Occitan",
  "sc" : "Sardinian",
  "ks" : "Kashmiri",
  "smn" : "Inari Sami",
  "moh" : "Mohawk",
  "gu" : "Gujarati",
  "af" : "Afrikaans",
  "dsb" : "Lower Sorbian",
  "kn" : "Kannada",
  "sl" : "Slovenian",
  "ku" : "Kurdish",
  "brx" : "Bodo",
  "gd" : "Scottish Gaelic",
  "nnh" : "Ngiemboon",
  "chr" : "Cherokee",
  "mn" : "Mongolian",
  "yo" : "Yoruba",
  "lv" : "Latvian",
  "jv" : "Javanese",
  "nb" : "Norwegian Bokmål",
  "en" : "English",
  "ur" : "Urdu",
  "ti" : "Tigrinya",
  "wo" : "Wolof",
  "khq" : "Koyra Chiini",
  "hsb" : "Upper Sorbian",
  "hmn" : "Hmong",
  "hu" : "Hungarian",
  "de" : "German",
  "tzm" : "Central Atlas Tamazight",
  "nus" : "Nuer",
  "kpe" : "Kpelle",
  "ebu" : "Embu",
  "sbp" : "Sangu",
  "myv" : "Erzya",
  "am" : "Amharic",
  "pl" : "Polish",
  "ccp" : "Chakma",
  "ga" : "Irish",
  "ka" : "Georgian",
  "kaj" : "Jju",
  "om" : "Oromo",
  "twq" : "Tasawaq",
  "ny" : "Nyanja",
  "seh" : "Sena",
  "luo" : "Luo",
  "ne" : "Nepali",
  "hi" : "Hindi",
  "it" : "Italian",
  "tn" : "Tswana",
  "sw" : "Swahili",
  "sn" : "Shona",
  "ar" : "Arabic",
  "ksh" : "Colognian",
  "jmc" : "Machame",
  "haw" : "Hawaiian",
  "iu" : "Inuktitut",
  "kea" : "Kabuverdianu",
  "mid" : "Mandaic",
  "mk" : "Macedonian",
  "gl" : "Galician",
  "bn" : "Bangla",
  "sr" : "Serbian",
  "rof" : "Rombo",
  "kam" : "Kamba",
  "uk" : "Ukrainian",
  "rm" : "Romansh",
  "xh" : "Xhosa",
  "mfe" : "Morisyen",
  "byn" : "Blin",
  "ts" : "Tsonga",
  "nn" : "Norwegian Nynorsk",
  "dyo" : "Jola-Fonyi",
  "kw" : "Cornish",
  "or" : "Odia",
  "bo" : "Tibetan",
  "lb" : "Luxembourgish",
  "raj" : "Rajasthani",
  "fa" : "Persian",
  "vi" : "Vietnamese",
  "agq" : "Aghem",
  "kk" : "Kazakh",
  "pt" : "Portuguese",
  "yav" : "Yangben",
  "mzn" : "Mazanderani",
  "mr" : "Marathi",
  "dav" : "Taita",
  "bs" : "Bosnian",
  "mer" : "Meru",
  "ko" : "Korean",
  "ast" : "Asturian",
  "fy" : "Western Frisian",
  "co" : "Corsican",
  "as" : "Assamese",
  "es" : "Spanish",
  "cgg" : "Chiga",
  "ja" : "Japanese",
  "sm" : "Samoan",
  "ia" : "Interlingua",
  "ki" : "Kikuyu",
  "hy" : "Armenian",
  "cy" : "Welsh",
  "tk" : "Turkmen",
  "be" : "Belarusian",
  "qu" : "Quechua",
  "tt" : "Tatar",
  "mni" : "Manipuri",
  "fil" : "Filipino",
  "teo" : "Teso",
  "jbo" : "Lojban",
  "guz" : "Gusii",
  "zgh" : "Tamazight, Standard Moroccan",
  "kcg" : "Tyap",
  "ca" : "Catalan",
  "dua" : "Duala",
  "br" : "Breton",
  "inh" : "Ingush",
  "ps" : "Pashto",
  "km" : "Khmer",
  "asa" : "Asu",
  "ak" : "Akan",
  "ee" : "Ewe",
  "mas" : "Masai",
  "mic" : "Mi'kmaw",
  "th" : "Thai",
  "arn" : "Mapuche",
  "nl" : "Dutch",
  "cho" : "Choctaw",
  "to" : "Tongan",
  "xog" : "Soga",
  "st" : "Southern Sotho",
  "apw" : "Apache, Western",
  "mg" : "Malagasy",
  "uz" : "Uzbek",
  "fr" : "French",
  "jgo" : "Ngomba",
  "mua" : "Mundang",
  "syr" : "Assyrian",
  "sat" : "Santali",
  "lkt" : "Lakota",
  "ckb" : "Kurdish, Sorani",
  "sk" : "Slovak",
  "mai" : "Maithili",
  "wal" : "Wolaytta",
  "kgp" : "Kaingang",
  "sd" : "Sindhi",
  "ce" : "Chechen",
  "el" : "Greek",
  "yrl" : "Nheengatu",
  "bm" : "Bambara",
  "gv" : "Manx",
  "nqo" : "N’Ko",
  "eo" : "Esperanto",
  "sq" : "Albanian",
  "ba" : "Bashkir",
  "rn" : "Rundi",
  "kde" : "Makonde",
  "my" : "Burmese",
  "lag" : "Langi",
  "gn" : "Guarani",
  "bez" : "Bena",
  "nnp" : "Wancho",
  "ff" : "Fula",
  "se" : "Northern Sami",
  "sg" : "Sango",
  "ain" : "Ainu",
  "rwk" : "Rwa",
  "nv" : "Navajo",
  "fur" : "Friulian",
  "bas" : "Basaa",
  "ss" : "Swati",
  "rw" : "Kinyarwanda",
  "sah" : "Sakha",
  "pcm" : "Nigerian Pidgin",
  "yi" : "Yiddish",
  "bem" : "Bemba",
  "tg" : "Tajik"
}

COUNTRIES = {
  "SX" : "Sint Maarten",
  "GA" : "Gabon",
  "EC" : "Ecuador",
  "SV" : "El Salvador",
  "AR" : "Argentina",
  "LA" : "Laos",
  "RO" : "Romania",
  "CF" : "Central African Republic",
  "TK" : "Tokelau",
  "BG" : "Bulgaria",
  "HT" : "Haiti",
  "AL" : "Albania",
  "AD" : "Andorra",
  "PG" : "Papua New Guinea",
  "OM" : "Oman",
  "ME" : "Montenegro",
  "JO" : "Jordan",
  "LC" : "St. Lucia",
  "GL" : "Greenland",
  "ST" : "São Tomé & Príncipe",
  "WF" : "Wallis & Futuna",
  "XK" : "Kosovo",
  "HN" : "Honduras",
  "TD" : "Chad",
  "SM" : "San Marino",
  "AW" : "Aruba",
  "MY" : "Malaysia",
  "BS" : "Bahamas",
  "KP" : "North Korea",
  "MR" : "Mauritania",
  "JE" : "Jersey",
  "BO" : "Bolivia",
  "SS" : "South Sudan",
  "MC" : "Monaco",
  "CR" : "Costa Rica",
  "NG" : "Nigeria",
  "CD" : "Congo - Kinshasa",
  "LU" : "Luxembourg",
  "UA" : "Ukraine",
  "GF" : "French Guiana",
  "AM" : "Armenia",
  "NP" : "Nepal",
  "BL" : "St. Barthélemy",
  "MS" : "Montserrat",
  "MH" : "Marshall Islands",
  "CN" : "China mainland",
  "CK" : "Cook Islands",
  "SJ" : "Svalbard & Jan Mayen",
  "AG" : "Antigua & Barbuda",
  "HU" : "Hungary",
  "TR" : "Türkiye",
  "SZ" : "Eswatini",
  "TH" : "Thailand",
  "AS" : "American Samoa",
  "CX" : "Christmas Island",
  "MT" : "Malta",
  "GD" : "Grenada",
  "SA" : "Saudi Arabia",
  "WS" : "Samoa",
  "CY" : "Cyprus",
  "BR" : "Brazil",
  "CV" : "Cape Verde",
  "SI" : "Slovenia",
  "LR" : "Liberia",
  "CL" : "Chile",
  "IL" : "Israel",
  "CG" : "Congo - Brazzaville",
  "AE" : "United Arab Emirates",
  "AF" : "Afghanistan",
  "ML" : "Mali",
  "MU" : "Mauritius",
  "GT" : "Guatemala",
  "NA" : "Namibia",
  "PF" : "French Polynesia",
  "PK" : "Pakistan",
  "SR" : "Suriname",
  "MP" : "Northern Mariana Islands",
  "UY" : "Uruguay",
  "VN" : "Vietnam",
  "SO" : "Somalia",
  "RS" : "Serbia",
  "CH" : "Switzerland",
  "EG" : "Egypt",
  "GU" : "Guam",
  "PT" : "Portugal",
  "SH" : "St. Helena",
  "MZ" : "Mozambique",
  "UM" : "U.S. Outlying Islands",
  "IT" : "Italy",
  "PH" : "Philippines",
  "BT" : "Bhutan",
  "IE" : "Ireland",
  "BN" : "Brunei",
  "AU" : "Australia",
  "LB" : "Lebanon",
  "FJ" : "Fiji",
  "BE" : "Belgium",
  "DO" : "Dominican Republic",
  "FI" : "Finland",
  "YT" : "Mayotte",
  "BY" : "Belarus",
  "IO" : "Chagos Archipelago",
  "SL" : "Sierra Leone",
  "CM" : "Cameroon",
  "NZ" : "New Zealand",
  "003" : "North America",
  "SD" : "Sudan",
  "CC" : "Cocos (Keeling) Islands",
  "EE" : "Estonia",
  "PM" : "St. Pierre & Miquelon",
  "NU" : "Niue",
  "KZ" : "Kazakhstan",
  "GN" : "Guinea",
  "MV" : "Maldives",
  "GY" : "Guyana",
  "JP" : "Japan",
  "TZ" : "Tanzania",
  "FR" : "France",
  "NC" : "New Caledonia",
  "MM" : "Myanmar (Burma)",
  "GI" : "Gibraltar",
  "PA" : "Panama",
  "IM" : "Isle of Man",
  "TM" : "Turkmenistan",
  "RW" : "Rwanda",
  "BZ" : "Belize",
  "US" : "United States",
  "PR" : "Puerto Rico",
  "ZM" : "Zambia",
  "SK" : "Slovakia",
  "MO" : "Macao",
  "LY" : "Libya",
  "CA" : "Canada",
  "LV" : "Latvia",
  "SE" : "Sweden",
  "DK" : "Denmark",
  "RE" : "Réunion",
  "MW" : "Malawi",
  "AZ" : "Azerbaijan",
  "KH" : "Cambodia",
  "CO" : "Colombia",
  "ZW" : "Zimbabwe",
  "SG" : "Singapore",
  "GH" : "Ghana",
  "BA" : "Bosnia & Herzegovina",
  "BM" : "Bermuda",
  "CU" : "Cuba",
  "TT" : "Trinidad & Tobago",
  "PY" : "Paraguay",
  "DZ" : "Algeria",
  "BD" : "Bangladesh",
  "ZA" : "South Africa",
  "AO" : "Angola",
  "TW" : "Taiwan",
  "PS" : "Palestinian Territories",
  "GB" : "United Kingdom",
  "LS" : "Lesotho",
  "PL" : "Poland",
  "KW" : "Kuwait",
  "ID" : "Indonesia",
  "BH" : "Bahrain",
  "IN" : "India",
  "BJ" : "Benin",
  "IC" : "Canary Islands",
  "LK" : "Sri Lanka",
  "TG" : "Togo",
  "KM" : "Comoros",
  "SC" : "Seychelles",
  "KY" : "Cayman Islands",
  "KN" : "St. Kitts & Nevis",
  "FO" : "Faroe Islands",
  "MN" : "Mongolia",
  "JM" : "Jamaica",
  "YE" : "Yemen",
  "PW" : "Palau",
  "NR" : "Nauru",
  "MD" : "Moldova",
  "DM" : "Dominica",
  "UG" : "Uganda",
  "BW" : "Botswana",
  "MK" : "North Macedonia",
  "TJ" : "Tajikistan",
  "150" : "Europe",
  "PE" : "Peru",
  "CW" : "Curaçao",
  "HK" : "Hong Kong",
  "DG" : "Diego Garcia",
  "FM" : "Micronesia",
  "GM" : "Gambia",
  "NF" : "Norfolk Island",
  "EH" : "Western Sahara",
  "NO" : "Norway",
  "VI" : "U.S. Virgin Islands",
  "GE" : "Georgia",
  "FK" : "Falkland Islands",
  "ER" : "Eritrea",
  "KI" : "Kiribati",
  "SY" : "Syria",
  "MQ" : "Martinique",
  "TV" : "Tuvalu",
  "MG" : "Madagascar",
  "TC" : "Turks & Caicos Islands",
  "VE" : "Venezuela",
  "CI" : "Côte d’Ivoire",
  "BI" : "Burundi",
  "BF" : "Burkina Faso",
  "IQ" : "Iraq",
  "HR" : "Croatia",
  "LI" : "Liechtenstein",
  "KG" : "Kyrgyzstan",
  "MF" : "St. Martin",
  "AI" : "Anguilla",
  "ET" : "Ethiopia",
  "VU" : "Vanuatu",
  "CZ" : "Czechia",
  "EA" : "Ceuta & Melilla",
  "AT" : "Austria",
  "AX" : "Åland Islands",
  "UZ" : "Uzbekistan",
  "KE" : "Kenya",
  "NE" : "Niger",
  "ES" : "Spain",
  "GG" : "Guernsey",
  "TO" : "Tonga",
  "419" : "Latin America",
  "VA" : "Vatican City",
  "BQ" : "Caribbean Netherlands",
  "VC" : "St. Vincent & Grenadines",
  "QA" : "Qatar",
  "IS" : "Iceland",
  "GR" : "Greece",
  "TN" : "Tunisia",
  "MA" : "Morocco",
  "GW" : "Guinea-Bissau",
  "SN" : "Senegal",
  "PN" : "Pitcairn Islands",
  "IR" : "Iran",
  "SB" : "Solomon Islands",
  "MX" : "Mexico",
  "RU" : "Russia",
  "VG" : "British Virgin Islands",
  "LT" : "Lithuania",
  "NI" : "Nicaragua",
  "GQ" : "Equatorial Guinea",
  "NL" : "Netherlands",
  "GP" : "Guadeloupe",
  "001" : "world",
  "TL" : "Timor-Leste",
  "DE" : "Germany",
  "DJ" : "Djibouti",
  "KR" : "South Korea",
  "BB" : "Barbados"
}